### PR TITLE
Puppet4

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by DavidS** [comment]
ruby is horrible. Have a look at https://github.com/puppetlabs/modulesync_configs/blob/master/config_defaults.yml#L42-L108 (or one of the supported modules' Gemfile) to crib the current state of play for json_pure and friends.

A more long-term solution that doesn't involve touching every module every time is planned for next sprint: https://tickets.puppetlabs.com/browse/MODULES-4027

**Comment by DavidS** [comment]
Otherwise it looks good from a code stand point, except for the failing tests.

**Comment by ghoneycutt** [comment]
The failing tests are not at all related to the addition Puppet v4 / Ruby 2.3.1. Could you merge as is? I'm adding this support to a bunch of puppetlabs modules and while I'm happy to get them in shape, I am running short on hours by debugging the ruby gem deps for older versions.

**Comment by ghoneycutt** [comment]
Thanks @DavidS much appreciated!

**Pull request merged**
