### PR TITLE
Configure git using the git class

### PR DESCRIPTION
**Pull request by ricoli**
Mainly for hiera usage purposes

### CODE REVIEW

**Comment by tphoney** [comment]
Thanks for the contribution, this is currently failing the unit tests. Can you please fix this. It also could do with some more tests to make sure this functionality will continue to work over time. Examples would be great as well.

**Comment by ricoli** [comment]
@tphoney from the travis output it seems that the tests were already broken before this PR, as the output points at indentation problems that do not relate to this PR:
```
manifests/config.pp - WARNING: indentation of => is not properly aligned on line 68
manifests/config.pp - WARNING: indentation of => is not properly aligned on line 69
manifests/config.pp - WARNING: indentation of => is not properly aligned on line 70
manifests/config.pp - WARNING: indentation of => is not properly aligned on line 71
```
Also, I have already updated the README in this PR with an example, is that what you mean by it?

**Comment by tphoney** [comment]
fixed the underlying lint issue

**Comment by tphoney** [comment]
A unit test or acceptance test would be my primary interest.

**Comment by ricoli** [comment]
sure thing, added a simple one :)

**Comment by ricoli** [comment]
and thank you for fixing the linting, build is now green!

**Comment by ricoli** [comment]
I wonder if you could also tag it?

**Comment by tphoney** [comment]
You would like this released on the forge ?

**Comment by ricoli** [comment]
If you don't mind, that would be great :)

**Comment by mbrodala** [comment]
This change is already wonderful to simplify Hiera data. :-)

But to make this really smooth in Hiera, something like this would be even greater:

```yaml
git::configs:
  user.name: 'test'
  user.email: 'test@test.com'
```

Any idea how this could be achieved with the built-in functions/stdlib?

**Comment by mbrodala** [comment]
Implementation in Ruby:

```ruby
configs = {"user.name" => {"value" => "test"}, "user.email" => "test@test.com"}
configs = Hash[configs.map {|k, v| [k, v.is_a?(Hash) ? v : {"value" => v}] }]
=> {"user.name"=>{"value"=>"test"}, "user.email"=>{"value"=>"test@test.com"}}
```

This would ensure the minimum expected structure for plain config values.

**Comment by ricoli** [comment]
@mbrodala feel free to submit a separate PR with it :)

**Comment by mbrodala** [comment]
Done with #64 :-)

**Pull request merged**
